// Generated by CoffeeScript 1.10.0
window.addEventListener("DOMContentLoaded", function() {
  var AudioContext, fn, i, id, len, option, options, ref, results, wavepots, wp;
  AudioContext = window.AudioContext || window.webkitAudioContext;
  if (AudioContext && !window.context) {
    window.context = new AudioContext();
    wavepots = {};
    ref = document.getElementsByClassName("wavepot");
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      wp = ref[i];
      id = wp.getAttribute("id");
      wavepots[id] = new WavepotRuntime({
        context: window.context,
        channels: 2,
        bufferSize: 1024,
        ratio: 1.0,
        oneliner: false
      });
      options = {
        'pause': function() {
          return wavepots[id].pause();
        },
        'play': function() {
          var compiled, text;
          text = wp.getElementsByTagName('pre')[0].innerHTML;
          compiled = wavepots.compile(text);
          if (compiled) {
            return wavepots[id].play();
          } else {
            return console.log("isn't possible to compile code");
          }
        }
      };
      results.push((function() {
        var results1;
        results1 = [];
        for (option in options) {
          fn = options[option];
          results1.push(wp.getElementsByClassName(option)[0].addEventListener('click', fn));
        }
        return results1;
      })());
    }
    return results;
  }
});
